export const ModuleNames = {
  user_permission: 'User Permission',
  user: 'User',
  user_list: 'User List',
  permission_module_type_map: 'Permission Module Type Mapping',
  permission_module_tab: 'Permission Module Tab',
  permission_module: 'Permission Module',
  permission_department: 'Permission Department',
  transfer: 'Transfer',
  file_manager: 'File Manager',
  branch: 'Branch',
  components: 'Components',
  components_notes: 'Components Notes',
  components_swap: 'Components Swap',
  parts_engineering: 'Parts Engineering',
  parts_inventory: 'Parts Inventory',
  parts: 'Parts',
  parts_history: 'Parts History',
  parts_pricing: 'Parts Pricing',
  vehicle_history: 'Vehicle History',
  vehicle: 'Vehicle',
  vehicle_activity: 'Vehicle Activity',
  vehicle_info: 'Vehicle Information',
  vehicle_inventory: 'Vehicle Inventory',
  vehicle_notes: 'Vehicle Notes',
  vendor: 'Vendor',
  vendor_activity: 'Vendor Activity',
  vendor_contact: 'Vendor Contact',
  vendor_footer: 'Vendor Footer',
  vendor_history: 'Vendor History',
  vendor_info: 'Vendor Information',
  vendor_notes: 'Vendor Notes',
  titles: 'Titles',
  divisional_revenue: 'Divisional Revenue',
  divisional_revenue_region: 'Divisional Revenue Region',
  customer: 'Customer',
  customer_activity: 'Customer Activity',
  customer_collection: 'Customer Collection',
  customer_contact: 'Customer Contact',
  customer_history: 'Customer History',
  customer_info: 'Customer Information',
  customer_notes: 'Customer Notes',
  devices: 'Devices',
  devices_history: 'Devices History',
  devices_info: 'Devices Information',
  devices_notes: 'Devices Notes',
  employee: 'Employee',
  employee_activity: 'Employee Activity',
  employee_certificate: 'Employee Certificate',
  employee_equip: 'Employee Equip',
  employee_history: 'Employee History',
  employee_more_info: 'Employee More Information',
  employee_notes: 'Employee Notes',
  employee_work: 'Employee Work',
  google_map_address: 'Google Map Address',
  fleet: 'Fleet',
  inventory_transfer_report: 'Inventory Transfer Report',
  purchase_order: 'Purchase Order',
  project_info: 'Project Information',
  bid_board: 'Bid Board',
  time_approval:'Time Approval',
  project_history:'Project History',
  physical_inventory:'Physical Inventory',
  per_diem_entry: 'Per Diem Entry',
};
